import {
  FaDigitalOcean,
  FaFacebookF,
  FaMicrosoft,
  FaUber,
} from "react-icons/fa";
import { SiAndela } from "react-icons/si";

export const jobs = [
  {
    id: "434n4j4SSjf",
    icon: { name: FaDigitalOcean, color: "blue.400" },
    match: 85,
    company: "Digital Ocean",
    position: "Sr. Back-End Developer",
    salary: {
      start: 8800,
      end: 12700,
    },
    location: "Lagos, Ayobo",
    tags: ["C++", "Open SG", "GPSS"],
    post_date: "29.03.2021",
    new: true,
    coords: [6.6054, 3.2438],
  },
  {
    id: "ffmwf9JJF89s",
    icon: { name: FaMicrosoft, color: "orange.400" },
    match: 54,
    company: "Microsoft",
    position: "Sr. Full-Stack Developer",
    salary: {
      start: 12000,
      end: 15000,
    },
    location: "Parkview Estate, Ikoyi",
    tags: ["C++", "Vue JS", "ELAN"],
    post_date: "24.03.2021",
    new: true,
    coords: [6.4588, 3.441],
  },
  {
    id: "fwf8Heg89ej",
    icon: { name: FaUber, color: "gray.900" },
    match: 23,
    company: "UBER",
    position: "Sr. Front End Dev & Sr. Full Stack Dev.",
    salary: {
      start: 23000,
      end: 24500,
    },
    location: "Lekki, Abijo",
    tags: ["mSQL", "YafaRay", "CSS3"],
    post_date: "22.03.2021",
    coords: [6.4531, 3.6775],
  },
  {
    id: "fwfjmi8Hf8sd",
    icon: { name: SiAndela, color: "orange.400" },
    match: null,
    company: "Andela",
    position: "Product Manager",
    salary: {
      start: 21000,
      end: 24300,
    },
    location: "Lekki, Chevyview Estate",
    tags: ["mSQL", "YafaRay", "CSS3"],
    post_date: "20.03.2021",
    coords: [6.4429, 3.5301],
  },
  {
    id: "fe8Hf7wfjkw99",
    icon: { name: FaFacebookF, color: "blue.700" },
    match: null,
    company: "Facebook",
    position: "Designer.",
    salary: {
      start: 21000,
      end: 24300,
    },
    location: "Lagos Island, Onikan",
    tags: ["Figma", "Dribble"],
    post_date: "19.03.2021",
    coords: [6.4417, 3.4019],
  },
];
